name: Pull Request CI

on:
  pull_request:
    branches: ['main']

jobs:
  check-license:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: License Eye Header
        uses: apache/skywalking-eyes@v0.7.0

  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x, 22.x, 24.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run linter
        run: npm run lint:check

      - name: Build package
        run: npm run build --if-present
        
  all-checks-passed:
    runs-on: ubuntu-latest
    needs: [test, build, check-license]
    if: always()

    steps:
      - name: Ensure all checks have passed
        run: echo "All checks have passed successfully!"

